/*******************************************************************************
 * This file is part of OpenNMS(R).
 *
 * Copyright (C) 2011-2012 The OpenNMS Group, Inc.
 * OpenNMS(R) is Copyright (C) 1999-2012 The OpenNMS Group, Inc.
 *
 * OpenNMS(R) is a registered trademark of The OpenNMS Group, Inc.
 *
 * OpenNMS(R) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * OpenNMS(R) is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenNMS(R).  If not, see:
 *      http://www.gnu.org/licenses/
 *
 * For more information contact:
 *     OpenNMS(R) Licensing <license@opennms.org>
 *     http://www.opennms.org/
 *     http://www.opennms.com/
 *******************************************************************************/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.03.17 at 12:58:43 PM EDT
//

package org.opennms.xmlns.xsd.event;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.opennms.xmlns.xsd.event package.
 * <p>
 * An ObjectFactory allows you to programmatically construct new instances of
 * the Java representation for XML content. The Java representation of XML
 * content can consist of schema derived interfaces and classes representing the
 * binding of schema type definitions, element declarations and model groups.
 * Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: org.opennms.xmlns.xsd.event
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Maskelement }.
     *
     * @return the maskelement
     */
    public Maskelement createMaskelement() {
        return new Maskelement();
    }

    /**
     * Create an instance of {@link Autoaction }.
     *
     * @return the autoaction
     */
    public Autoaction createAutoaction() {
        return new Autoaction();
    }

    /**
     * Create an instance of {@link Header }.
     *
     * @return the header
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Tticket }.
     *
     * @return the tticket
     */
    public Tticket createTticket() {
        return new Tticket();
    }

    /**
     * Create an instance of {@link Logmsg }.
     *
     * @return the logmsg
     */
    public Logmsg createLogmsg() {
        return new Logmsg();
    }

    /**
     * Create an instance of {@link Parm }.
     *
     * @return the parm
     */
    public Parm createParm() {
        return new Parm();
    }

    /**
     * Create an instance of {@link Script }.
     *
     * @return the script
     */
    public Script createScript() {
        return new Script();
    }

    /**
     * Create an instance of {@link Correlation }.
     *
     * @return the correlation
     */
    public Correlation createCorrelation() {
        return new Correlation();
    }

    /**
     * Create an instance of {@link Parms }.
     *
     * @return the parms
     */
    public Parms createParms() {
        return new Parms();
    }

    /**
     * Create an instance of {@link Forward }.
     *
     * @return the forward
     */
    public Forward createForward() {
        return new Forward();
    }

    /**
     * Create an instance of {@link Autoacknowledge }.
     *
     * @return the autoacknowledge
     */
    public Autoacknowledge createAutoacknowledge() {
        return new Autoacknowledge();
    }

    /**
     * Create an instance of {@link AlarmData }.
     *
     * @return the alarm data
     */
    public AlarmData createAlarmData() {
        return new AlarmData();
    }

    /**
     * Create an instance of {@link Log }.
     *
     * @return the log
     */
    public Log createLog() {
        return new Log();
    }

    /**
     * Create an instance of {@link Events }.
     *
     * @return the events
     */
    public Events createEvents() {
        return new Events();
    }

    /**
     * Create an instance of {@link Value }.
     *
     * @return the value
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link Mask }.
     *
     * @return the mask
     */
    public Mask createMask() {
        return new Mask();
    }

    /**
     * Create an instance of {@link Snmp }.
     *
     * @return the snmp
     */
    public Snmp createSnmp() {
        return new Snmp();
    }

    /**
     * Create an instance of {@link Operaction }.
     *
     * @return the operaction
     */
    public Operaction createOperaction() {
        return new Operaction();
    }

    /**
     * Create an instance of {@link Event }.
     *
     * @return the event
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link EventReceipt }.
     *
     * @return the event receipt
     */
    public EventReceipt createEventReceipt() {
        return new EventReceipt();
    }

}
